site_name: My Docs

nav:
  - Home: index.md
  - Quick Start Guide: quick_start.md
  - Wiki:
      - Sensorset 2026.L: wiki/sensorset2026-l.md
      - Pacmod 3: wiki/pacmod_actuation.md

theme:
  name: material
  palette:
    scheme: youtube
  features:
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true

extra_css:
  - stylesheets/extra.css
