/camera:
  ros__parameters:
    camera_info_url: ''
    diagnostic_updater:
      period: 1.0
    feature/AcquisitionFrameCount: 1
    feature/AcquisitionFrameRateAbs: 20.0
    feature/AcquisitionFrameRateLimit: 33.88681802778719
    feature/AcquisitionMode: Continuous
    feature/ActionDeviceKey: 0
    feature/ActionGroupKey: 0
    feature/ActionGroupMask: 0
    feature/ActionSelector: 0
    feature/BalanceRatioAbs: 2.33
    feature/BalanceRatioSelector: Red
    feature/BalanceWhiteAuto: 'Off'
    feature/BalanceWhiteAutoAdjustTol: 5
    feature/BalanceWhiteAutoRate: 100
    feature/BandwidthControlMode: StreamBytesPerSecond
    feature/BinningHorizontal: 1
    feature/BinningVertical: 1
    feature/BlackLevel: 4.0
    feature/BlackLevelSelector: All
    feature/ChunkModeActive: false
    feature/ColorTransformationMode: 'Off'
    feature/ColorTransformationSelector: RGBtoRGB
    feature/ColorTransformationValue: 1.0
    feature/ColorTransformationValueSelector: Gain00
    feature/DSPSubregionBottom: 1544
    feature/DSPSubregionLeft: 0
    feature/DSPSubregionRight: 2064
    feature/DSPSubregionTop: 0
    feature/DecimationHorizontal: 1
    feature/DecimationVertical: 1
    feature/DeviceFirmwareVersion: '00.01.54.40105 '
    feature/DeviceID: 50-0537031346
    feature/DeviceModelName: Mako G-319C
    feature/DevicePartNumber: '9615'
    feature/DeviceScanType: Areascan
    feature/DeviceTemperature: 54.0
    feature/DeviceTemperatureSelector: Main
    feature/DeviceUserID: ''
    feature/DeviceVendorName: Allied Vision Technologies
    feature/EventAcquisitionEnd: 40001
    feature/EventAcquisitionEndFrameID: 0
    feature/EventAcquisitionEndTimestamp: 0
    feature/EventAcquisitionRecordTrigger: 40004
    feature/EventAcquisitionRecordTriggerFrameID: 0
    feature/EventAcquisitionRecordTriggerTimestamp: 0
    feature/EventAcquisitionStart: 40000
    feature/EventAcquisitionStartFrameID: 0
    feature/EventAcquisitionStartTimestamp: 0
    feature/EventAction0: 40020
    feature/EventAction0FrameID: 0
    feature/EventAction0Timestamp: 0
    feature/EventAction1: 40021
    feature/EventAction1FrameID: 0
    feature/EventAction1Timestamp: 0
    feature/EventError: 65535
    feature/EventErrorFrameID: 0
    feature/EventErrorTimestamp: 0
    feature/EventExposureEnd: 40003
    feature/EventExposureEndFrameID: 0
    feature/EventExposureEndTimestamp: 0
    feature/EventExposureStart: 40019
    feature/EventExposureStartFrameID: 0
    feature/EventExposureStartTimestamp: 0
    feature/EventFrameTrigger: 40002
    feature/EventFrameTriggerFrameID: 0
    feature/EventFrameTriggerReady: 40018
    feature/EventFrameTriggerReadyFrameID: 0
    feature/EventFrameTriggerReadyTimestamp: 0
    feature/EventFrameTriggerTimestamp: 0
    feature/EventLine1FallingEdge: 40011
    feature/EventLine1FallingEdgeFrameID: 0
    feature/EventLine1FallingEdgeTimestamp: 0
    feature/EventLine1RisingEdge: 40010
    feature/EventLine1RisingEdgeFrameID: 0
    feature/EventLine1RisingEdgeTimestamp: 0
    feature/EventLine2FallingEdge: 40013
    feature/EventLine2RisingEdge: 40012
    feature/EventNotification: 'Off'
    feature/EventOverflow: 65534
    feature/EventOverflowFrameID: 0
    feature/EventOverflowTimestamp: 0
    feature/EventPtpSyncLocked: 40006
    feature/EventPtpSyncLockedFrameID: 0
    feature/EventPtpSyncLockedTimestamp: 0
    feature/EventPtpSyncLost: 40005
    feature/EventPtpSyncLostFrameID: 0
    feature/EventPtpSyncLostTimestamp: 0
    feature/EventSelector: AcquisitionStart
    feature/EventsEnable1: 0
    feature/ExposureAuto: 'Off'
    feature/ExposureAutoAdjustTol: 5
    feature/ExposureAutoAlg: Mean
    feature/ExposureAutoMax: 499999
    feature/ExposureAutoMin: 16
    feature/ExposureAutoOutliers: 0
    feature/ExposureAutoRate: 100
    feature/ExposureAutoTarget: 50
    feature/ExposureMode: Timed
    feature/ExposureTimeAbs: 15000.0
    feature/ExposureTimeIncrement: 1.0
    feature/FirmwareVerBuild: 40105
    feature/FirmwareVerMajor: 1
    feature/FirmwareVerMinor: 54
    feature/GVCPCmdRetries: 5
    feature/GVCPCmdTimeout: 250
    feature/GVSPBurstSize: 1
    feature/GVSPDriver: Socket
    feature/GVSPFilterVersion: N/A
    feature/GVSPHostReceiveBufferSize: 67108864
    feature/GVSPMaxLookBack: 30
    feature/GVSPMaxRequests: 1
    feature/GVSPMaxWaitSize: 100
    feature/GVSPMissingSize: 256
    feature/GVSPPacketSize: 1500
    feature/GVSPTiltingSize: 100
    feature/GVSPTimeout: 70
    feature/Gain: 0.0
    feature/GainAuto: 'Off'
    feature/GainAutoAdjustTol: 5
    feature/GainAutoMax: 40.0
    feature/GainAutoMin: 0.0
    feature/GainAutoOutliers: 0
    feature/GainAutoRate: 100
    feature/GainAutoTarget: 50
    feature/GainSelector: All
    feature/Gamma: 1.0
    feature/GevCurrentDefaultGateway: 0
    feature/GevCurrentIPAddress: 389086889
    feature/GevCurrentSubnetMask: 65535
    feature/GevDeviceMACAddress: 65252753202
    feature/GevHeartbeatInterval: 1450
    feature/GevHeartbeatTimeout: 3000
    feature/GevIPConfigurationMode: DHCP
    feature/GevPersistentDefaultGateway: 0
    feature/GevPersistentIPAddress: 763100841
    feature/GevPersistentSubnetMask: 65535
    feature/GevSCPSPacketSize: 1500
    feature/GevTimestampTickFrequency: 1000000000
    feature/GevTimestampValue: 0
    feature/Height: 1544
    feature/HeightMax: 1544
    feature/Hue: 0.0
    feature/ImageSize: 3186816
    feature/LUTAddress: 196608
    feature/LUTBitDepthIn: 12
    feature/LUTBitDepthOut: 12
    feature/LUTEnable: false
    feature/LUTIndex: 0
    feature/LUTMode: Luminance
    feature/LUTSelector: LUT1
    feature/LUTSizeBytes: 8192
    feature/LUTValue: 4095
    feature/MulticastEnable: false
    feature/MulticastIPAddress: 4026470193
    feature/NonImagePayloadSize: 0
    feature/OffsetX: 0
    feature/OffsetY: 0
    feature/PayloadSize: 3186816
    feature/PixelFormat: BayerRG8
    feature/PtpAcquisitionGateTime: 0
    feature/PtpMode: 'Off'
    feature/PtpStatus: Disabled
    feature/RecorderPreEventCount: 0
    feature/ReverseX: false
    feature/ReverseY: false
    feature/Saturation: 1.0
    feature/SensorBits: 12
    feature/SensorHeight: 1544
    feature/SensorType: Bayer
    feature/SensorWidth: 2064
    feature/StatFrameDelivered: 0
    feature/StatFrameDropped: 0
    feature/StatFrameRate: 0.0
    feature/StatFrameRescued: 0
    feature/StatFrameShoved: 0
    feature/StatFrameUnderrun: 0
    feature/StatLocalRate: 0.0
    feature/StatPacketErrors: 0
    feature/StatPacketMissed: 0
    feature/StatPacketReceived: 0
    feature/StatPacketRequested: 0
    feature/StatPacketResent: 0
    feature/StatPacketUnavailable: 0
    feature/StatTimeElapsed: 0.0
    feature/StreamAnnounceBufferMinimum: 1
    feature/StreamAnnouncedBufferCount: 0
    feature/StreamBufferHandlingMode: Default
    feature/StreamBytesPerSecond: 115000000
    feature/StreamFrameRateConstrain: true
    feature/StreamHoldCapacity: 19
    feature/StreamHoldEnable: 'Off'
    feature/StreamID: DEV_000F315DFF32-Stream-000
    feature/StreamType: GEV
    feature/StrobeDelay: 0
    feature/StrobeDuration: 0
    feature/StrobeDurationMode: Source
    feature/StrobeSource: FrameTrigger
    feature/SyncInGlitchFilter: 0
    feature/SyncInLevels: 0
    feature/SyncInSelector: SyncIn1
    feature/SyncOutLevels: 0
    feature/SyncOutPolarity: Normal
    feature/SyncOutSelector: SyncOut1
    feature/SyncOutSource: Exposing
    feature/TriggerActivation: RisingEdge
    feature/TriggerDelayAbs: 0.0
    feature/TriggerMode: 'On'
    feature/TriggerOverlap: 'Off'
    feature/TriggerSelector: FrameStart
    feature/TriggerSource: FixedRate
    feature/UserSetDefaultSelector: Default
    feature/UserSetSelector: Default
    feature/Width: 2064
    feature/WidthMax: 2064
    frame_id: ''
    guid: ''
    ip: 192.168.1.223
    ptp_offset: 0
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
    use_measurement_time: false
    use_sim_time: false

