/**:
  ros__parameters:
    sensor_hostname: '192.168.10.23' # 'os-122542002319.local'
    udp_dest: '192.168.10.5'
    mtp_dest: ''
    mtp_main: false
    lidar_mode: '1024x10'
    timestamp_mode: 'TIME_FROM_ROS_TIME'
    udp_profile_lidar: 'RNG19_RFL8_SIG16_NIR16'
    metadata: ''
    lidar_port: 7507
    imu_port: 7506
    sensor_frame: 'lexus3/os_left_sensor'
    lidar_frame: 'lexus3/os_left'
    imu_frame: 'lexus3/os_left_imu'
    use_system_default_qos: false