ouster/os_sensor:
  ros__parameters:
    sensor_hostname: 'os-122231000907.local'
    udp_dest: '192.168.1.5'
    mtp_dest: ''
    mtp_main: false
    lidar_mode: '1024x20'
    timestamp_mode: 'TIME_FROM_ROS_TIME'
    udp_profile_lidar: ''
    metadata: ''
    lidar_port: 7503
    imu_port: 7502
ouster/os_cloud:
  ros__parameters:
    sensor_frame: 'lexus3/os_right_a'
    lidar_frame: 'lexus3/os_right_a_laser_data_frame'
    imu_frame: 'lexus3/os_right_a_imu_data_frame'
    timestamp_mode: 'TIME_FROM_ROS_TIME'  # this value needs to match os_sensor/timestamp_mode
