ouster/os_sensor:
  ros__parameters:
    sensor_hostname: 'os-992219000350.local'
    udp_dest: '192.168.1.5'
    mtp_dest: ''
    mtp_main: false
    lidar_mode: '1024x20'
    timestamp_mode: 'TIME_FROM_ROS_TIME'
    udp_profile_lidar: ''
    metadata: ''
    lidar_port: 7505
    imu_port: 7504
ouster/os_cloud:
  ros__parameters:
    sensor_frame: 'lexus3/os_center_a'
    lidar_frame: 'lexus3/os_center_a_laser_data_frame'
    imu_frame: 'lexus3/os_center_a_imu_data_frame'
    timestamp_mode: 'TIME_FROM_ROS_TIME'  # this value needs to match os_sensor/timestamp_mode
