# [Not recommended] Use this configuration only when utilizing the disjointed
# os_sensor and os_cloud configuration
# For the future and for better results consider migrating to combined node/component os_driver
# and utilize the driver_params.yaml along with it. 
lexus3/os_center/os_sensor:
  ros__parameters:
    sensor_hostname: '192.168.10.20'
    udp_dest: '192.168.10.5'
    mtp_dest: ''
    mtp_main: false
    lidar_mode: '1024x10'
    timestamp_mode: 'TIME_FROM_ROS_TIME'
    udp_profile_lidar: 'RNG19_RFL8_SIG16_NIR16'
    metadata: ''
    lidar_port: 7505
    imu_port: 7504
    use_system_default_qos: false
    azimuth_window_start: 0
    azimuth_window_end: 360000
    persist_config: false
    attempt_reconnect: false
    dormant_period_between_reconnects: 1.0
    max_failed_reconnect_attempts: 2147483647
lexus3/os_center/os_cloud:
  ros__parameters:
    sensor_frame: lexus3/os_center_a
    lidar_frame: lexus3/os_center_a_laser_data_frame
    imu_frame: lexus3/os_center_a_imu_data_frame
    point_cloud_frame: lexus3/os_center_a
    timestamp_mode: 'TIME_FROM_ROS_TIME'  # this value needs to match os_sensor/timestamp_mode
    ptp_utc_tai_offset: -37.0 # UTC/TAI offset in seconds to apply when using TIME_FROM_PTP_1588
    proc_mask: PCL # pick IMU, PCL, SCAN or any combination of the three options
    use_system_default_qos: false # needs to match the value defined for os_sensor node
    scan_ring: 0  # Use this parameter in conjunction with the SCAN flag and choose a
                  # value the range [0, sensor_beams_count)
    point_type: original # choose from: {original, native, xyz, xyzi, xyzir}
lexus3/os_center/os_image:
    use_system_default_qos: false # needs to match the value defined for os_sensor node
lexus3/os_right/os_sensor:
  ros__parameters:
    sensor_hostname: '192.168.10.21'
    udp_dest: '192.168.10.5'
    mtp_dest: ''
    mtp_main: false
    lidar_mode: '1024x10'
    timestamp_mode: 'TIME_FROM_ROS_TIME'
    udp_profile_lidar: 'RNG19_RFL8_SIG16_NIR16'
    metadata: ''
    lidar_port: 7503
    imu_port: 7502
    use_system_default_qos: false
    azimuth_window_start: 0
    azimuth_window_end: 360000
    persist_config: false
    attempt_reconnect: false
    dormant_period_between_reconnects: 1.0
    max_failed_reconnect_attempts: 2147483647
lexus3/os_right/os_cloud:
  ros__parameters:
    sensor_frame: lexus3/os_right_a
    lidar_frame: lexus3/os_right_a_laser_data_frame
    imu_frame: lexus3/os_right_a_imu_data_frame
    point_cloud_frame: lexus3/os_right_a
    timestamp_mode: 'TIME_FROM_ROS_TIME'  # this value needs to match os_sensor/timestamp_mode
    ptp_utc_tai_offset: -37.0 # UTC/TAI offset in seconds to apply when using TIME_FROM_PTP_1588
    proc_mask: PCL # pick IMU, PCL, SCAN or any combination of the three options
    use_system_default_qos: false # needs to match the value defined for os_sensor node
    scan_ring: 0  # Use this parameter in conjunction with the SCAN flag and choose a
                  # value the range [0, sensor_beams_count)
    point_type: original # choose from: {original, native, xyz, xyzi, xyzir}
lexus3/os_right/os_image:
    use_system_default_qos: false # needs to match the value defined for os_sensor node
