lexus3/os_pcl_merger_node:
  ros__parameters:
    topics: ["lexus3/os_left/points","lexus3/os_right/points"]
    frames: ["lexus3/os_left_a_laser", "lexus3/os_right_a_laser", "lexus3/os_center_a_laser"]
    children_frames: ["lexus3/os_left_a", "lexus3/os_right_a", "lexus3/os_center_a"]
