lexus3/os_center/os_driver:
  ros__parameters:
    sensor_hostname: 'os-992219000350.local'
    udp_dest: '192.168.1.5'
    mtp_dest: ''
    mtp_main: false
    lidar_mode: '1024x20'
    timestamp_mode: 'TIME_FROM_ROS_TIME'
    udp_profile_lidar: 'RNG19_RFL8_SIG16_NIR16'
    metadata: ''
    lidar_port: 7505
    imu_port: 7504
    sensor_frame: 'lexus3/os_center_a'
    lidar_frame: 'lexus3/os_center_a_laser_data_frame'
    imu_frame: 'lexus3/os_center_a_imu_data_frame'
    use_system_default_qos: true    
lexus3/os_center/os_cloud:
  ros__parameters:
    timestamp_mode: 'TIME_FROM_ROS_TIME'  # this value needs to match os_sensor/timestamp_mode
lexus3/os_right/os_driver:
  ros__parameters:
    sensor_hostname: 'os-122231000907.local'
    udp_dest: '192.168.1.5'
    mtp_dest: ''
    mtp_main: false
    lidar_mode: '1024x20'
    timestamp_mode: 'TIME_FROM_ROS_TIME'
    udp_profile_lidar: 'RNG19_RFL8_SIG16_NIR16'
    metadata: ''
    lidar_port: 7503
    imu_port: 7502
    sensor_frame: 'lexus3/os_right_a'
    lidar_frame: 'lexus3/os_right_a_laser_data_frame'
    imu_frame: 'lexus3/os_right_a_imu_data_frame'
    use_system_default_qos: true    
lexus3/os_right/os_cloud:
  ros__parameters:
    timestamp_mode: 'TIME_FROM_ROS_TIME'  # this value needs to match os_sensor/timestamp_mode
lexus3/os_left/os_driver:
  ros__parameters:
    sensor_hostname: 'os-122227001628.local'
    udp_dest: '192.168.1.5'
    mtp_dest: ''
    mtp_main: false
    lidar_mode: '1024x20'
    timestamp_mode: 'TIME_FROM_ROS_TIME'
    udp_profile_lidar: 'RNG19_RFL8_SIG16_NIR16'
    metadata: ''
    lidar_port: 7507
    imu_port: 7506
    sensor_frame: 'lexus3/os_left_a'
    lidar_frame: 'lexus3/os_left_a_laser_data_frame'
    imu_frame: 'lexus3/os_left_a_imu_data_frame'
    use_system_default_qos: true
lexus3/os_left/os_cloud:
  ros__parameters:
    timestamp_mode: 'TIME_FROM_ROS_TIME'  # this value needs to match os_sensor/timestamp_mode    