lexus3/os_pcl_merger_node:
  ros__parameters:
    topics: ["/lexus3/os_left/points","/lexus3/os_right/points"]
    frames: ["lexus3/os_left_b_laser", "lexus3/os_right_b_laser"]
    children_frames: ["lexus3/os_left_a", "lexus3/os_right_a"]
    target_frame: "os_sensor"
    pub_topic_name: "merged_points"